services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis_db
    networks:
      - app-network
    restart: unless-stopped

  redis_db:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:

