version: '3.8'

services:
  flask_app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis_db
    networks:
      - app-network
    restart: always

  redis_db:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:

